Bump Thor dep to 1.3, because code is not compatible with 1.0 anymore
With Thor 1.0, the following error araise:
```
$ kameleon template list
Recipe templates available in: /home/pneyron/.kameleon.d/repos
Resolving templates (100%)
......................................................................................................................................................ᗧ
Error: uninitialized constant Thor::Shell::Terminal
Unfortunately, a fatal error has occurred : uninitialized constant
Thor::Shell::Terminal.
Use --debug option for more details
```